import 'package:flutter/material.dart';

class ConstIcons {
  ConstIcons._();

  static const List<IconData> icons = [
    Icons.menu_book_outlined,
    Icons.library_books_outlined,
    Icons.bookmark_border_outlined,
    Icons.school_outlined,
    Icons.assignment_outlined,
    Icons.quiz_outlined,
    Icons.psychology_outlined,
    Icons.edit_note_outlined,
    Icons.assignment_turned_in_outlined,
    Icons.text_fields_outlined,
    Icons.spellcheck_outlined,
    Icons.translate_outlined,
    Icons.mic_outlined,
    Icons.volume_up_outlined,
    Icons.headphones_outlined,
    Icons.search_outlined,
    Icons.category_outlined,
    Icons.label_outlined,
    Icons.folder_outlined,
    Icons.edit_outlined,
    Icons.delete_outline,
    Icons.add_circle_outline,
    Icons.close_outlined,
    Icons.check_circle_outlined,
    Icons.share_outlined,
    Icons.download_outlined,
    Icons.upload_outlined,
    Icons.save_outlined,
    Icons.trending_up_outlined,
    Icons.bar_chart_outlined,
    Icons.favorite_border_outlined,
    Icons.star_border_outlined,
    Icons.settings_outlined,
    Icons.home_outlined,
    Icons.lightbulb_outline,
    Icons.info_outline,
    Icons.help_outline,
    Icons.notifications_outlined,
    Icons.access_time_outlined,
    Icons.date_range_outlined,
    Icons.person_outline,
    Icons.group_outlined,
  ];
}
